### PR TITLE
Added support for CentOS7.

### PR DESCRIPTION
**Pull request by svallero**
In the dependencies I temporarily put: ansible-role-docker (local clone of git branch devel).
This needs to be modified once the support for Centos7 is added to the docker role in Galaxy.

### CODE REVIEW

**Comment by maricaantonacci** [comment]
I have the following comment:
why did you add a new docker image for zookeeper (based on centos 7)? The already available indigodatacloud/zookeeper (based on ubuntu 14.04) should run both on EL and Debian-based systems..

**Comment by rfc1459** [comment]
I agree with Marica: the two things that should be changed are the [hardcoded reference to eth0](https://github.com/indigo-dc/ansible-role-zookeeper/blob/e97f873ec112d6966f1619ccc481f8b24ba43169/defaults/main.yml#L19) in `main.yml` (which can cause some issues on CentOS 7 due to systemd-udev and biosdevname) and the metadata for Ansible Galaxy in order to declare support for EL 7 hosts.

Using different Docker images for different host systems is neither required nor advised.

**Comment by svallero** [comment]
The CentOS 7 image is indeed not strictly necessary. My misunderstanding, I thought we also wanted a CentOS version.  Still, I do not agree with the statement "nor advised". For a number of reasons some people might prefer to work with an EL 7 system. 
Reference to eth0: you are right !!! It escaped my attention since for consistency I use the old naming scheme on my hosts. I take care of it. 
I think we should discuss in the mailing list wether to discard this pull request and only keep the Ubuntu image.
Also: if we decide to strip things down to the bare minimum of what is really required to run the service, I think we should not go for a "huge" distro like Ubuntu or CentOS, but prefer a minimal image like microbox or similar. Keep in mind that for other services that might require the sharing of host system libraries (not in this case), using the same distro makes your life easier.

**Comment by svallero** [comment]
In the second commit I have removed the 2 misleading config files for Ubuntu/RHEL and corrected the hardcoded reference to eth0 as discussed.

**Comment by rfc1459** [comment]
Looks good to me, +1 for merging

**Comment by maricaantonacci** [comment]
OK for me too. I'm merging the pull request. Thanks.

**Pull request merged**
